name: ci-cd

on:
  push:
    tags:
      - v*

jobs:
  build_ios:
    name: Flutter Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - run: |
          echo "Creating IPA file from Runner.app"
          mkdir -p build/ios/iphoneos/Payload
          mv build/ios/iphoneos/Runner.app/ build/ios/iphoneos/Payload
          cd build/ios/iphoneos/Payload/Runner.app
          zip ../../app-unsigned.ipa
      - run: rm -rf build/ios/iphoneos/Payload
      
      # - name: Push IPA to Releases
      #   uses: ncipollo/release-action@v1.10.0
      #   with:
      #     artifacts: "build/ios/iphoneos/*.ipa"
      #     token: !!! required for this package

      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: app-unsigned-ios
          path: build/ios/iphoneos/app-unsigned.ipa

  build-android:
    name: Flutter Build Android AppBundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build appbundle
      - run: flutter build apk --debug --split-per-abi
      
      # - name: Push APK to Releases
      #   uses: ncipollo/release-action@v1.10.0
      #   with:
      #     artifacts: "build/app/outputs/apk/debug/*.apk"
      #     token: !!! required for this package

      - name: Upload AppBundle
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
