name: ci-cd

on:
  push:
    tags:
      - v*

jobs:
  build_ios:
    name: Flutter Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build ios --release --no-codesign
      - run: mkdir -p build/ios/iphoneos/Payload
      - run: mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload
      - uses: thedoctor0/zip-release@main
        with:
          type: zip
          directory: build/ios/iphoneos/
          path: Payload
          filename: app.zip
      - run: rm -rf Payload
      - run: mv build/ios/iphoneos/app.zip build/ios/iphoneos/app.ipa
      # - name: Push IPA to Releases
      #   uses: ncipollo/release-action@v1.10.0
      #   with:
      #     artifacts: "build/ios/iphoneos/*.ipa"
      - name: Upload IPA
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: app ipa
          path: build/ios/iphoneos/app.ipa

  build-android:
    name: Flutter Build Android AppBundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v2.6.1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build appbundle
      - run: flutter build apk --debug --split-per-abi
      # - name: Push APK to Releases
      #   uses: ncipollo/release-action@v1.10.0
      #   with:
      #     artifacts: "build/app/outputs/apk/debug/*.apk"
      - name: Upload AppBundle
        uses: actions/upload-artifact@v3.1.0
        with: 
          name: appbundle
          path: build/app/outputs/bundle/release/app-release.aab
